### ISSUE TITLE
PyPI package includes integration_test as top-level package

### ISSUE THREAD

**Issue by reupen** [alphagov/notifications-python-client#205]
Hi,

I noticed that the PyPI package includes `integration_test` as a top-level package.

This means that after installing the package (e.g. `pip install notifications-python-client`) you can do things like:

```python
import integration_test
from integration_test.integration_tests import get_template_by_id
```

This isn't causing me a problem, but it could lead to accidental imports or conflicts etc. (as `integration_test` is a pretty generic package name).

(In my case, I ended up there when searching for uses of `NotificationsAPIClient` in my IDE, and was a bit confused for a second...)

**Comment by quis** [comment]
Hey, thanks for taking the time to raise the issues. We recently fixed this in one of our other packages so I’ve raised [a pull request](https://github.com/alphagov/notifications-python-client/pull/206/files) with the same fix for this package.

**Comment by ushkarev** [comment]
I've just noticed that this package still packages a bunch of test files that are not relevant and that #206 has been closed. Do you perhaps want a PR with a fix?

**Comment by reupen** [comment]
> I've just noticed that this package still packages a bunch of test files that are not relevant 

Indeed, it installs both `tests` and `integration_test` packages.

**Comment by ushkarev** [comment]
…and looking in the latest wheel, `utils` too!

**Comment by samuelhwilliams** [comment]
🙇‍♂️  Thanks for putting up this PR @ushkarev - we will try to take a look at this soon with a view to getting it merged 🎉
